### ISSUE TITLE
Autocomplete Ajax data

### ISSUE THREAD

**Issue by slabcloud** [CodyHouse/cd-autocomplete-changelog#1]
I am trying to use the Autocomplete component for state/city suggestions.
Since I'm using the whole US and Canada database, it is not effective to load this amount of data on page load.
I need to use keyup event and get the data from the Restful API  server.
How do I do that with Autocomplete component?

**Comment by claudia-romano** [comment]
Hi there,
you can use the `searchData` option to retrieve your results from the server. You can find more details on the component Info page:
https://codyhouse.co/ds/components/info/autocomplete
